### PR TITLE
socket: fix compilation for non-linux targets

### PR DESCRIPTION
**Pull request by Hummer12007**

### CODE REVIEW

**Comment by antoyo** [comment]
Thanks.
I'll try this on a BSD.

**Comment by Hummer12007** [comment]
So, got any chance to test? This fixed build on OS X for me (at the very least).
On second test, tests/examples do not build yet. Will work on it.

**Comment by antoyo** [comment]
No, I've been very busy these last weeks.
I'll try to test it this weekend.
Some examples might not work on non-Linux because they use abstract domain socket which are only supported on Linux.
Thanks for your work!

**Comment by antoyo** [comment]
Thank you for your contribution.

**Pull request merged**
